---
#################################################
# ConfigMap for index.html for mydata v4
#################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: mydata-cm-v4
data:
  index.html: |
    <body bgcolor="green">
      <center>
        <h1>Ini Aplikasi</h1>
        <h1>V4</h1>
      </center>
    </body>
---
#################################################
# Deployment: mydata v4
#################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydata-v4
  labels:
    app: mydata
    version: v4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydata
      version: v4
  template:
    metadata:
      labels:
        app: mydata
        version: v4
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: index-html
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: index-html
        configMap:
          name: mydata-cm-v4
